name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - dev/*
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "23.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: install protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: generate protobuf code
        run: |
          export PATH=../../../go/bin:${PATH}
          protoc --go_out=. --go_opt=paths=source_relative ./pkg/event/v1/event.proto
          # got to remove the packages we just installed so that
          # the linter doesn't complain.
          sudo rm -rf ../../../go/pkg/mod/google.golang.org/protobuf*

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.54.2

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
